config/routes.rb
Rails.application.routes.draw do

  resources :books do
    scope module: :book do
      resources :pages
    end

    member do
      get :download
    end
  end
  root to: "page#root"

end

app/models/book.rb
class Book < ActiveRecord::Base
  has_many :pages, class_name: 'Book::Page'

  def to_epub
    book = self
    epub = EeePub.make do
      title(book.title)
      uid('BookId')
      identifier(SecureRandom.uuid, scheme: :uuid, id: 'BookId')

      files book.pages.map { |page| page.to_html }
    end

    path = Rails.root.join('tmp', 'epub', "#{id}.epub").to_s
    FileUtils.mkdir_p(File.dirname(path))
    epub.save(path)

    path
  end
end

app/models/book/page.rb
class Book::Page < ActiveRecord::Base
  belongs_to :book
  mount_uploader :image, PageUploader

  def to_html
    @size = FastImage.size(image.path)
    @type = FastImage.type(image.path)
    @blob = Base64.encode64(File.open(image.path, 'rb', &:read))

    template = ERB.new(File.read(
      Rails.root.join('app', 'views', 'book', 'pages', 'content.html.erb')
    ))
    html = template.result(binding)  #テンプレートで書いたHTMLファイルが入る

    path = Rails.root.join('tmp', 'page',"#{id}.html").to_s
    FileUtils.mkdir_p(File.dirname(path))
    File.open(path, 'w') do |file|
      file.write(html)
    end
    path
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/book/pages_controller.rb
class Book::PagesController < ApplicationController
  before_action :set_book_page, only: [:show, :edit, :update, :destroy]

  # GET /book/pages
  # GET /book/pages.json
  def index
    @book_pages = book.pages.all
  end

  # GET /book/pages/1
  # GET /book/pages/1.json
  def show
  end

  # GET /book/pages/new
  def new
    @book_page = Book::Page.new
  end

  # GET /book/pages/1/edit
  def edit
  end

  # POST /book/pages
  # POST /book/pages.json
  def create
    @book_page = Book::Page.new(book_page_params.merge(book: book)) #変更

    respond_to do |format|
      if @book_page.save
        format.html { redirect_to book_pages_path(book_id: book.id), notice: 'Page was successfully created.' }
        format.json { render :show, status: :created, location: @book_page }
      else
        format.html { render :new }
        format.json { render json: @book_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /book/pages/1
  # PATCH/PUT /book/pages/1.json
  def update
    respond_to do |format|
      if @book_page.update(book_page_params)
        format.html { redirect_to @book_page, notice: 'Page was successfully updated.' }
        format.json { render :show, status: :ok, location: @book_page }
      else
        format.html { render :edit }
        format.json { render json: @book_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /book/pages/1
  # DELETE /book/pages/1.json
  def destroy
    @book_page.destroy
    respond_to do |format|
      format.html { redirect_to book_pages_url, notice: 'Page was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def book
      @book ||= Book.find(params[:book_id]) #現在指している本が帰ってくる
    end

    helper_method :book  #htnlにアクセスできるようになる

    # Use callbacks to share common setup or constraints between actions.
    def set_book_page
      @book_page = book.pages.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_page_params
      params.require(:book_page).permit(:book_id, :image)
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  #URLからもらった処理から本を引いてくる処理を追加
  before_action :set_book, only: [:show, :edit, :update, :destroy, :download]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def download
    path = @book.to_epub
    blob = File.open(path, 'rb', &:read)


    send_data blob,
      type: 'application/epub+zip',
      filename: "#{@book.title}.epub",
      disposition: :attachment
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :description)
    end
end

app/controllers/page_controller.rb
class PageController < ApplicationController

  def root
    render plain: "Hello rails"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book/pages_helper.rb
module Book::PagesHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/views/book/pages/_form.html.erb
<%= form_for(@book_page) do |f| %>
  <% if @book_page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book_page.errors.count, "error") %> prohibited this book_page from being saved:</h2>

      <ul>
      <% @book_page.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/book/pages/content.html.erb
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta name="viewport" content="width=<%= @size[0] %>, height=<%= @size[1] %>">
  <style>
    html, body{
      width: 100%;
      height: 100%;
      margin: 0;
      padding: 0;
    }
    img, svg{
      margin: 0;
      padding: 0;
      border: 0;
    }
  </style>
</head>
<body>
  <svg xmlns="http://www.w3.org/2000/svg" version="1.1"
    xmlns:xlink="http://www.w3.org/1999/xlink"
    width="100%" height="100%" viewBox="0 0 <%= @size[0] %> <%= @size[1] %>"
  >
  <image
    width="<%= @size[0] %>"
    height="<%= @size[1] %>"
    xlink:href="data:image/<%= @type %>;base64,<%= @blob %>"
  >
</body>
</html>

app/views/book/pages/edit.html.erb
<h1>Editing Book Page</h1>

<%= render 'form' %>

<%= link_to 'Show', @book_page %> |
<%= link_to 'Back', book_pages_path %>

app/views/book/pages/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= book.title %>のページ一覧</h1>

<table>
  <thead>
    <tr>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @book_pages.each do |book_page| %>
      <tr>
        <td class="with-image"><img width="200px" src="<%= book_page.image.url %>"></td>
        <!--td><%= link_to 'Show', book_page_path(book_id: book.id, id: book_page.id) %></td>
        <td><%= link_to 'Edit', edit_book_page_path(book_id: book.id, id: book_page.id) %></td-->
        <td class="with-button"><%= link_to '消す', book_page_path(book_id: book.id, id: book_page.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Page', new_book_page_path %>

app/views/book/pages/new.html.erb
<h1>New Book Page</h1>

<%= render 'form' %>

<%= link_to 'Back', book_pages_path %>

app/views/book/pages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Book:</strong>
  <%= @book_page.book %>
</p>

<p>
  <strong>Image:</strong>
  <%= @book_page.image %>
</p>

<%= link_to 'Edit', edit_book_page_path(@book_page) %> |
<%= link_to 'Back', book_pages_path %>

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>町の本屋さん</h1>

<table>
  <thead>
    <tr>
      <th>書籍名</th>
      <th>説明</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.description %></td>
        <td><%= link_to '見る', book_path(id: book.id) %></td>
        <td><%= link_to '編集する', edit_book_path(book) %></td>
        <td><%= link_to '消す', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '新しく本を作る', new_book_path %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form' %>

<%= link_to '戻る', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @book.description %>
</p>

<%= link_to 'Download', download_book_path(@book) %> |
<%= link_to 'Pages', book_pages_path(book_id: @book.id) %> |
<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Example</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="container">
  <%= yield %>
</div>

</body>
</html>